{% set name = "Orange3" %}
{% set version = "3.34.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Orange3-{{ version }}.tar.gz
  sha256: ae80147a9f2b2b2454fa806ca41a4dbd00e6c12a71e6e8ff19fe8e01d3d12d01

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main
  osx_is_app: true
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - numpy
    - pip
    - setuptools
    - wheel
    - python
    - recommonmark
    - sphinx >=4.2.0
    - docutils <0.17  # docutils changed html template in 0.17
  run:
    # appnope should be in orange-widget-base
    - appnope  # [osx]
    - anyqt >=0.1.0
    - baycomp >=1.0.2
    - bottleneck >=1.3.4
    - chardet >=3.0.2
    - httpx >=0.21
    - joblib >=0.11
    - keyring
    - keyrings.alt
    - matplotlib-base >=3.2.0
    - networkx
    - numpy >=1.19.5
    - openpyxl
    - opentsne >=0.6.1
    - orange-canvas-core >=0.1.28,<0.2a
    - orange-widget-base >=4.19.0
    - pandas >=1.3.0,!=1.5.0
    - pip >=18.0
    - pygments >=2.8.0
    - pyqt >5.15.1
    - pyqtgraph >=0.12.2,!=0.12.4
    - pyqtwebengine >=5.12
    - python
    - python-louvain >=0.13
    - pyyaml
    - qtconsole >=4.7.2
    - requests
    - scikit-learn >=1.0.1,<1.2.0
    - scipy >=1.9
    - serverfiles
    - setuptools >=41.0.0
    # xgboost is optional since user must install libomp (with brew) on macOS for xgboost to work
    # it is not required for xgboost from conda - it is why I am adding a package to the recipe
    - xgboost
    - catboost !=1.0.0
    - xlrd >=1.2.0
    - xlsxwriter
    # python3.7 on conda-forge has build problems due to incompatibility between required
    # setuptools between ipykernel and some other libraries:
    # https://github.com/ipython/ipykernel/pull/900
    - ipykernel !=6.11.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - Orange
    - Orange.canvas
  commands:
    - python -c "import pkg_resources; pkg_resources.require('Orange3')"
    - orange-canvas --help
    - export QT_QPA_PLATFORM=offscreen  # [not win]
    # for now, only test on Windows (better have some tests than none)
    - python -m unittest -v Orange.tests Orange.widgets.tests  # [win]
  requires:
    - pip

app:
  entry: orange-canvas
  summary: data visualization and data analysis tool
  icon: icon_48x48.png
about:
  home: http://orange.biolab.si/
  summary: Orange, a component-based data mining framework.
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: component-based data mining framework
  description: |
    Open source data visualization and data analysis for novice and expert.
    Interactive workflows with a large toolbox.
  doc_url: http://orange.biolab.si/docs/
  dev_url: https://github.com/biolab/orange3

extra:
  recipe-maintainers:
    - lanzagar
    - ales-erjavec
    - markotoplak
    - primozgodec
