{% set version = "3.27.0" %}
{% set sha256 = "9b48f8f96acbecd03b0dc180472b5d0b1f3249e7f3dab2a9cc01f0d366947b0b" %}

package:
  name: orange3
  version: {{ version }}

source:
  fn: Orange3-{{ version }}.tar.gz
  url: https://github.com/biolab/orange3/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main
  osx_is_app: true
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - wheel
    - numpy 1.14
  run:
    - python
    - setuptools >=36.3
    - numpy >=1.16.0
    - scipy >=0.16.1
    - scikit-learn >=0.22.0,!=0.23.0
    - bottleneck >=1.0.0
    - chardet >=3.0.2
    - docutils
    - xlrd >=0.9.2
    - xlsxwriter
    - anyqt >=0.0.8
    - pyqtgraph >=0.11.0
    - joblib >=0.9.4
    - keyring
    - keyrings.alt
    - pip >=9.0
    - python.app  # [osx]
    - serverfiles
    - python-louvain >=0.13
    - requests
    - matplotlib-base >=2.0.0
    - openTSNE >=0.4.3
    - pandas
    - pyyaml
    - orange-canvas-core >=0.1.16,<0.2a
    - orange-widget-base >=4.8.1
    - openpyxl
    - httpx =0.14.*
    - baycomp >=1.0.2
    # cachecontrol (required by canvas core) <0.12.5 is incompatible with msgpack 1.0
    - cachecontrol >=0.12.6
    # appnope should be in orange-widget-base TODO: add it to next release, or find different solution
    - appnope  # [osx]

test:
  commands:
    - python -c "import pkg_resources; pkg_resources.require('Orange3')"
    - orange-canvas --help
  imports:
    - Orange

app:
  entry: orange-canvas
  summary: data visualization and data analysis tool
  icon: icon_48x48.png

about:
  home: http://orange.biolab.si
  license: GPL-3.0-only
  license_file: LICENSE
  summary: component-based data mining framework
  description: |
    Open source data visualization and data analysis for novice and expert.
    Interactive workflows with a large toolbox.
  doc_url: http://orange.biolab.si/docs/
  dev_url: https://github.com/biolab/orange3

extra:
  recipe-maintainers:
    - astaric
    - lanzagar
    - ales-erjavec
    - nikicc
    - markotoplak
    - primozgodec
    - carlodri
