{% set name = "Orange3" %}
{% set version = "3.38.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 6c6d3fa82e01fdc16187ef027cebb91537eae5b129ba31d3bb4bbfdab5fbb4f4

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main
  osx_is_app: true
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cython >=3.0
    - numpy
    - pip
    - setuptools >=51.0
    - wheel
    - python
    - recommonmark
    - sphinx >=4.2.0,<8
    - trubar >=0.3.4
  run:
    # appnope should be in orange-widget-base
    - appnope  # [osx]
    # gui requirements
    - orange-canvas-core >=0.2.5,<0.3a
    - orange-widget-base >=4.25.0
    - anyqt >=0.2.0
    - matplotlib-base >=3.2.0
    - pygments >=2.8.0
    - pyqt >5.15.1
    - pyqtgraph >=0.13.1
    - pyqtwebengine >=5.12
    - qtconsole >=4.7.2
    # core requirements
    - baycomp >=1.0.2
    - bottleneck >=1.3.4
    - catboost >=1.0.1
    - chardet >=3.0.2
    - httpx >=0.21.0
    - joblib >=1.2.0
    - keyring
    - keyrings.alt
    - networkx
    - numpy >=1.20.0,<2
    - openpyxl >=3.1.3
    - opentsne >=0.6.1,!=0.7.0,!=1.0.2
    - packaging
    - pandas >=1.4.0,!=1.5.0,!=2.0.0
    - pip >=19.3
    - python
    - python-louvain >=0.13
    - pyyaml
    - requests
    - scikit-learn >=1.5.1
    - scipy >=1.9
    - serverfiles
    - xgboost >=1.7.4,<2.1
    - xlrd >=1.2.0
    - xlsxwriter
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - Orange
    - Orange.canvas
  commands:
    - orange-canvas --help
    - export QT_QPA_PLATFORM=offscreen  # [not win]
    # for now, only test on Windows (better have some tests than none)
    - python -m unittest -v Orange.tests Orange.widgets.tests  # [win]
  requires:
    - pip

app:
  entry: orange-canvas
  summary: data visualization and data analysis tool
  icon: icon_48x48.png
about:
  home: http://orange.biolab.si/
  summary: Orange, a component-based data mining framework.
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    Open source data visualization and data analysis for novice and expert.
    Interactive workflows with a large toolbox.
  doc_url: http://orange.biolab.si/docs/
  dev_url: https://github.com/biolab/orange3

extra:
  recipe-maintainers:
    - lanzagar
    - ales-erjavec
    - markotoplak
    - primozgodec
