{% set name = "Orange3" %}
{% set version = "3.37.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Orange3-{{ version }}.tar.gz
  sha256: 9116612e42c2a7524fa8c8e000d8f5f1f8a728dabb837993e2b50a3c2e3d94f9

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main
  osx_is_app: true
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cython >=3.0
    - numpy
    - pip
    - setuptools >=51.0
    - wheel
    - python
    - recommonmark
    - sphinx >=4.2.0
  run:
    # appnope should be in orange-widget-base
    - appnope  # [osx]
    # gui requirements
    - orange-canvas-core >=0.1.30,<0.2a
    - orange-widget-base >=4.22.0
    - anyqt >=0.2.0
    - matplotlib-base >=3.2.0
    - pygments >=2.8.0
    - pyqt >5.15.1
    - pyqtgraph >=0.13.1
    - pyqtwebengine >=5.12
    - qtconsole >=4.7.2
    # core requirements
    - baycomp >=1.0.2
    - bottleneck >=1.3.4
    - catboost >=1.0.1
    - chardet >=3.0.2
    - httpx >=0.21.0
    - joblib >=1.0.0
    - keyring
    - keyrings.alt
    - networkx
    - numpy >=1.20.0
    - openpyxl
    - opentsne >=0.6.1,!=0.7.0
    - pandas >=1.4.0,!=1.5.0,!=2.0.0
    - pip >=18.0
    - python
    - python-louvain >=0.13
    - pyyaml
    - requests
    - scikit-learn >=1.1.0,!=1.2.*,<1.4
    - scipy >=1.9
    - serverfiles
    - setuptools >=51.0.0
    - xgboost >=1.7.4
    - xlrd >=1.2.0
    - xlsxwriter
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - Orange
    - Orange.canvas
  commands:
    - orange-canvas --help
    - export QT_QPA_PLATFORM=offscreen  # [not win]
    # for now, only test on Windows (better have some tests than none)
    # temporarily skipped; try again when pythoneditor tests pass on Orange's CI
    # - python -m unittest -v Orange.tests Orange.widgets.tests  # [win]
  requires:
    - pip

app:
  entry: orange-canvas
  summary: data visualization and data analysis tool
  icon: icon_48x48.png
about:
  home: http://orange.biolab.si/
  summary: Orange, a component-based data mining framework.
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    Open source data visualization and data analysis for novice and expert.
    Interactive workflows with a large toolbox.
  doc_url: http://orange.biolab.si/docs/
  dev_url: https://github.com/biolab/orange3

extra:
  recipe-maintainers:
    - lanzagar
    - ales-erjavec
    - markotoplak
    - primozgodec
