{% set name = "Orange3" %}
{% set version = "3.30.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Orange3-{{ version }}.tar.gz
  sha256: 6caa9888bbbf2a926d3a51418678d8e242ff4383bb7dd948fd690628a9d2eefa

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main
  osx_is_app: true
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - numpy
    - pip
    - setuptools
    - wheel
    - python
    - recommonmark
    - sphinx
  run:
    # appnope should be in orange-widget-base
    - appnope  # [osx]
    - anyqt >=0.0.11
    - baycomp >=1.0.2
    - bottleneck >=1.0.0
    - chardet >=3.0.2
    - httpx >=0.14.0,<0.20
    - joblib >=0.9.4
    - keyring
    - keyrings.alt
    - matplotlib-base >=2.0.0
    - networkx
    - numpy >=1.16.0
    - openpyxl
    - opentsne >=0.6.0
    - orange-canvas-core >=0.1.22,<0.2a
    - orange-widget-base >=4.14.0
    - pandas >=1.0.0
    - pip >=9.0
    - pygments >=2.8.0
    - pyqt >=5.12,!=5.15.1
    - pyqtgraph >=0.11.1
    - pyqtwebengine >=5.12
    - python
    - python-louvain >=0.13
    - pyyaml
    - qtconsole >=4.7.2
    - requests
    - scikit-learn >=0.22.0,!=0.23.0
    - scipy >=0.16.1
    - serverfiles
    - setuptools >=36.3
    # xgboost is optional since user must install libomp (with brew) on macOS for xgboost to work
    # it is not required for xgboost from conda - it is why I am adding a package to the recipe
    - xgboost
    - catboost  # [not linux and not py39]
    - xlrd >=0.9.2
    - xlsxwriter
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - Orange
    - Orange.canvas
  commands:
    - python -c "import pkg_resources; pkg_resources.require('Orange3')"
    - orange-canvas --help
  requires:
    - pip

app:
  entry: orange-canvas
  summary: data visualization and data analysis tool
  icon: icon_48x48.png
about:
  home: http://orange.biolab.si/
  summary: Orange, a component-based data mining framework.
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: component-based data mining framework
  description: |
    Open source data visualization and data analysis for novice and expert.
    Interactive workflows with a large toolbox.
  doc_url: http://orange.biolab.si/docs/
  dev_url: https://github.com/biolab/orange3

extra:
  recipe-maintainers:
    - astaric
    - lanzagar
    - ales-erjavec
    - nikicc
    - markotoplak
    - primozgodec
    - carlodri
