appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Rzr/DMNd+xPhqOboBJO0hz4bLA/iiysN/WNJWGw7m5HhccERFuVxWpipIl2AK2AT4XMKI/kYRluCCFZfE46lP7rQB3c/FcTtDnhUW1O7BWpq4tUuX0Fl9G64Mem2KnXVb/qJ91nv6rEokLCPd0locJHcgt2avyoEHr2qzRkU2doeY4CZd2d+/EJGq5ZJ+dBaa4Z9+kw8q8QxpEUOJOR52BaErqI/tbqbM4N4Ug5ljZqQAaj96C1lzSeL/SXDvZfUOPxtvp1orwvpy/oCi0OqqexrCDSPTOiafekQeF/AvibZvftGGPMQmFxcKYnW8HRfQMxMFsi0pGHmvbeh+QgNjO77x7UCzhgU56bDr/lYPkylVaYaN0PT5RJgwtt1DWWyEYAmnDlilCnOI9102hg+ku2plS7vq9U+QXYbOzKVBnPnQhl3+uukDJGbM9BGCMQcsQLiYmTAdeVIYjwesp8ywD8V5Jjh96/ysHrESan7TMpa9w4XNLtypctcCa37xMJWpDtOb3GyhODBYODt76u3q5vBftCR7hCSQuPjl/Sk8Cy9atXIUaGypc2kR9qtdq5zY+JRbcphUS7KzTsYyZ51h02pCyWSzvb8aDwDNKqvnsR8tu0fWz25NHTQ+SNLDf60pPPr95xI16hHJixdleBYxl/GGm4R1vqP78MXgSe2SzY=}
